listening-port=3478
# tls-listening-port=5349
external-ip=192.168.1.77
fingerprint
lt-cred-mech
realm=simple-chat.local
user=testuser:testpass
userdb=/var/lib/coturn/turnuserdb.conf
no-multicast-peers
no-cli
verbose
